plugins { id 'com.android.application' }
android {
    namespace 'com.retrojet.oyun'
    compileSdk 34
    defaultConfig {
        applicationId 'com.retrojet.oyun'
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName '1.3'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
